name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 */15 * * *' # Her 15 saatte bir çalışır
    
jobs:
  build-and-run:
    runs-on: windows-latest

    steps:
      # Kodun repo'dan indirilmesi
      - name: Checkout Code
        uses: actions/checkout@v3

      # PowerShell'in en son sürümünün kurulması
      - name: Install PowerShell
        run: |
          Invoke-WebRequest -Uri https://github.com/PowerShell/PowerShell/releases/download/v7.4.6/PowerShell-7.4.6-win-x64.msi -OutFile $env:TEMP\PowerShell-7.4.6-win-x64.msi
          Start-Process msiexec.exe -ArgumentList '/i', "$env:TEMP\PowerShell-7.4.6-win-x64.msi", '/quiet', '/norestart' -NoNewWindow -Wait
          pwsh -Command "Install-Module -Name PowerShellGet -Force -AllowClobber"
          pwsh -Command "Update-Module -Name PowerShellGet"
          pwsh -Command "Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force"

      # Java ortamının ayarlanması
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      # Chrome ve ChromeDriver'ın kurulması
      - name: Set up Chrome
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile "$env:TEMP\chrome_installer.exe"
          Start-Process -FilePath "$env:TEMP\chrome_installer.exe" -ArgumentList "/silent /install" -NoNewWindow -Wait
          Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_win32.zip" -OutFile "$env:TEMP\chromedriver.zip"
          Expand-Archive -Path "$env:TEMP\chromedriver.zip" -DestinationPath "$env:ProgramFiles\Google\Chrome\Application"

      - name: Verify Google Chrome Version
        run: |
          & "C:\Program Files\Google\Chrome\Application\chrome.exe" --version

      # MongoDB'nin kurulması
      - name: Install MongoDB
        run: |
          choco install mongodb -y
          if (-not (Get-Service -Name MongoDB -ErrorAction SilentlyContinue)) {
            net start MongoDB
          }

      # Maven ile projenin derlenmesi
      - name: Build with Maven (if needed)
        run: |
          if (!(Test-Path -Path './demo/target/demo-0.0.1-SNAPSHOT.jar')) {
            mvn clean install
          }
        working-directory: ./demo

      # MongoDB'nin hazır olup olmadığını kontrol etme
      - name: Wait for MongoDB
        run: |
          $attempts = 0
          while ($attempts -lt 20) {
            if (netstat -an | Select-String "27017") {
              Write-Output "MongoDB is ready!"
              exit 0
            }
            Write-Output "Waiting for MongoDB..."
            Start-Sleep -Seconds 5
            $attempts++
          }
          Write-Output "MongoDB did not start in time."
          exit 1

      # Uygulamanın çalıştırılması
      - name: Run Application
        run: java -jar demo/target/demo-0.0.1-SNAPSHOT.jar