name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *' # Her 5 dakikada bir çalışır

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Kodun repo'dan indirilmesi
      - name: Checkout Code
        uses: actions/checkout@v3

      # Java ortamının ayarlanması
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      # Chrome ve ChromeDriver'ın kurulması
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget unzip
          # Download ChromeDriver
          wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          sudo unzip /tmp/chromedriver.zip -d /usr/local/bin/
          # Download and install Google Chrome
          wget -q -O /tmp/google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i /tmp/google-chrome.deb || sudo apt-get install -y -f

      - name: Verify Chrome and ChromeDriver Versions
        run: |
          google-chrome --version
          chromedriver --version

      # Build with Maven
      - name: Build with Maven
        run: mvn clean install
        working-directory: ./demo

      # Wait for MongoDB to be ready
      - name: Wait for MongoDB
        run: |
          for i in {1..20}; do
            if nc -z localhost 27017; then
              echo "MongoDB is ready!"
              exit 0
            fi
            echo "Waiting for MongoDB..."
            sleep 5
          done
          echo "MongoDB did not start in time."
          exit 1

      # Uygulamanın çalıştırılması
      - name: Run Application
        run: |
          java -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver \
               -Dwebdriver.chrome.whitelistedIps='' \
               -Dwebdriver.chrome.args='--no-sandbox --disable-dev-shm-usage --headless --disable-gpu --remote-debugging-port=9222' \
               -Dserver.port=8081 \
               -jar demo/target/demo-0.0.1-SNAPSHOT.jar