name: Market Scraping Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Install dependencies and build the project
      - name: Build with Maven
        run: mvn clean install

      # Set up MongoDB service
      - name: Set up MongoDB
        uses: supercharge/mongodb-github-action@v1.7.0
        with:
          mongodb-version: '5.0' # Use your desired version

      # Run the Spring Boot application
      - name: Run Application
        run: mvn spring-boot:run
