name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *' # Her 5 dakikada bir çalışır

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Kodun repo'dan indirilmesi
      - name: Checkout Code
        uses: actions/checkout@v3

      # Java ortamının ayarlanması
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      # Chrome ve ChromeDriver'ın kurulması
      - name: Set up Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          sudo unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
          sudo apt-get install -y google-chrome-stable

      # Maven bağımlılıklarının yüklenmesi ve derlenmesi
      - name: Build with Maven
        run: mvn clean install
        working-directory: ./demo # demo klasörüne git

      # MongoDB'nin hazır olup olmadığını kontrol etme
      - name: Wait for MongoDB
        run: |
          for i in {1..20}; do
            if nc -z localhost 27017; then
              echo "MongoDB is ready!"
              exit 0
            fi
            echo "Waiting for MongoDB..."
            sleep 5
          done
          echo "MongoDB did not start in time."
          exit 1

      # Uygulamanın çalıştırılması
      - name: Run Application
        run: |
          java -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver \
               -Dwebdriver.chrome.whitelistedIps='' \
               -Dwebdriver.chrome.args='--no-sandbox --disable-dev-shm-usage --headless --disable-gpu --remote-debugging-port=9222' \
               -jar demo/target/demo-0.0.1-SNAPSHOT.jar